name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          # Set production environment variables
          export GENERATE_SOURCEMAP=false
          export REACT_APP_ENVIRONMENT=production
          npm run build
        
      - name: Clean build artifacts
        run: |
          cd build
          # Remove any remaining problematic files
          find . -name "*.map" -delete
          find . -name "*.gz" -delete
          find . -name "*.br" -delete
          find . -name "*.LICENSE.txt" -delete
          # Remove any hidden files
          find . -name ".*" -delete
          # Ensure clean structure
          echo "Build contents after cleaning:"
          ls -la
          echo "Total size:"
          du -sh .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
